#!/bin/bash

# optional argument handling
if [[ "$1" == "version" ]]
then
    echo "1.0.0"
    exit 0
fi

# optional argument handling
if [[ "$1" == "config" ]]
then
    echo "$KUBECONFIG"
    exit 0
fi
# optional argument handling
if [[ "$1" == "vms" ]]
then
    echo "List of VMs"
    # this binary is in /usr/lobal/bin
    svt-vms
    exit 0
fi
# optional argument handling
if [[ "$1" == "hosts" ]]
then
    echo "List of Hosts"
    # this binary is in /usr/lobal/bin
    svt-hosts
    exit 0
fi

echo "I am a plugin named kubectl-svt for hpe simplivity"